# header
title: delicate
menu:
  Home: /
  Archives: /archives

# --------------------------- #
##  siderbar infomation      ##
# --------------------------- #
## sidebar-about
siderbar:
  name: Kart · Jim
  logo: Time wait for no one.
  tag: 
    - 学生
    - 前端开发者
    - hexo菜鸟开发者
    - delicate主题开发者
  social: 
    ## 社交账户链接
    bilibili: https://space.bilibili.com
    github: https://github.com/can-dy-jack
    twitter: https://twitter.com
    CSDN: 
    codepen: 
    google: http://localhost:4000
    facebook: 
    stackoverflow: 
    linkedin: 
    slack: http://localhost:4000
    instagram: 
    gitlab: 
    贴吧: 
    知乎: 
    微博: 
    博客园: 
    掘金: 
    dingding: 

# --------------------------- #
## 背景                      ##
# --------------------------- #
background: 
  # meditation | point | line | line2
  ## 如果不填或填其它值，就是默认的白色背景
  default: ''
  # canvas制作的动态3D背景
  ## canvas线的颜色可以去文件(delicate/source/js/canvas.js)内去手动修改！
  canvas: true
  # three.js
  # 如需要添加背景three.js，需要defaut: false
  ## 还没做好！
  threeJs: 
    enable: false
    ## 3D模型
    type: 


# --------------------------- #
##   样式                     ##
# --------------------------- #
# Read More text 
excerpt_link: 'Read More'
style: 
  # 置顶文章的样式
  ## 基于bootstrap，可选项即为bootstrap的alert样式;默认：'alert alert-light'
  ### more：https://v4.bootcss.com/docs/components/alerts/
  ## use,just like: 'alert alert-primary'
  top: 'alert alert-info'
  # '阅读更多' 的按钮样式
  ## 基于bootstrap，可选项即为bootstrap的按钮样式
  ## btn-primary | btn-secondary | btn-secondary | btn-outline-success  and so on.
  ## more: https://v4.bootcss.com/docs/components/buttons/
  ## just like: 'btn btn-outline-success';
  button: ''

  


# --------------------------- #
##   评论系统                 ##
# --------------------------- #

utterance: 
## 仓库需要安装utterances https://github.com/apps/utterances
  enable: false
  repo: 
  issue_term: delicate-utterance
  # github-light | github-dark | preferred-color-scheme | github-dark-orange | icy-dark | dark-blue | photon-dark | boxy-light | gruvbox-dark
  ## 在线观看每个主题效果：https://utteranc.es/
  theme: 'github-light'

gittalk: 
  ## Firstly, you need choose a public github repository for store comment.
  ## A GitHub Application : https://github.com/settings/applications/new
  ### more: https://github.com/gitalk/gitalk
  enable: false
  # 您的评论存放的仓库名字
  repo: ''
  owner: ''
  admin: ['',]
  # GitHub Application Client ID and Client Secret
  clientID: ''
  clientSecret: ''
