# --------------------------------------------------------- #
#
#                         router
#
# --------------------------------------------------------- #
router:
  tags: true
  

# --------------------------------------------------------- #
#
#                      head and footer
#
# --------------------------------------------------------- #
## meta
# 当前文档的创建者
creator: ""
# 当前文档的发布者/出版者
publisher: ""

## link
# icon
icon: "/img/logo.ico"
# 导航栏上的图标
icon128: "/img/logo128.ico"

# nav友情链接
nav:
  friends:
    github: "https://github.com/can-dy-jack/hexo-theme-delicate"
    LeetCode: "https://leetcode-cn.com/u/kartjim/"
    CSDN: "https://blog.csdn.net/qq_46590483"
    掘金: "https://juejin.cn/user/1389392813630526"
    微博: "https://weibo.com/p/1005057198677513/home"

## footer - 建站起始时间
# 格式：- "2021-11-01T00:00:00"（默认本地时区）
# - "01 Nov 2021 00:00:00 +0800"（东八区，偏离格林威治8个小时）
startTime: "2021-11-01T00:00:00"

# --------------------------------------------------------- #
#
#                        styles
#
# --------------------------------------------------------- #

# 未实现
# 鼠标点击效果；
mouseClick:
  # 点击出现文字效果
  showText:
    enable: false
    text: ["富强", "民主", "文明", "和谐", "美丽"]
    color: "red"
  # 鼠标点击 - 心形
  # 心是随机颜色
  showHeart: false

markdownColor:
  post:
    table: "rgb(248, 229, 175)"
    table_tr: "rgba(248, 229, 175, .1)"
    table_border: "rgba(248, 229, 175)"

# --------------------------------------------------------- #
#
#                   index and post
#
# --------------------------------------------------------- #
# 主页配置
index:
  # 首页标头文字
  title: "hexo主题之delicate"
  # 阅读更多按钮
  excerpt:
    text: "阅读更多"

# post页面
post:
  share:
    qq: true
    weibo: true

# --------------------------------------------------------- #
#
#                   tags页面
#
# --------------------------------------------------------- #
# 标签云 tagcloud
tags: 
  # 标签云页面title
  title: ''
  # 最小字体尺寸
  min_font: 16
  # 最大字体尺寸
  max_font: 35
  # 字体尺寸的单位
  unit: 'px'
  # 标签总量
  amount: 900
  # 开始的颜色和结束的颜色
  ## 您可使用十六进位值（#b700ff），rgba（rgba(183, 0, 255, 1)），hsla（hsla(283, 100%, 50%, 1)）或 [颜色关键字]
  start_color: '#00eeee'
  end_color: '#004444'



