# --------------------------------------------------------- #
# 
#                      head and footer
# 
# --------------------------------------------------------- #
## meta
# 当前文档的创建者
creator: ''
# 当前文档的发布者/出版者
publisher: ''

## link
# icon
icon: '/img/logo.ico'
# 导航栏上的图标
icon128: '/img/logo128.ico'

# nav友情链接
nav: 
  friends: 
    github: 'https://github.com/can-dy-jack/hexo-theme-delicate'
    CSDN: 'https://blog.csdn.net/qq_46590483'


## footer - 建站起始时间
# 格式：- "2021-11-01T00:00:00"（默认本地时区）
# - "01 Nov 2021 00:00:00 +0800"（东八区，偏离格林威治8个小时）
startTime: "2021-11-01T00:00:00"


# --------------------------------------------------------- #
# 
#                        styles
# 
# --------------------------------------------------------- #

# 未实现
# 鼠标点击效果；
mouseClick:
  # 点击出现文字效果
  showText:
    enable: false
    text: ['富强','民主','文明','和谐','美丽']
    color: 'red'
  # 鼠标点击 - 心形
  # 心是随机颜色
  showHeart: false

# --------------------------------------------------------- #
# 
#                           index
# 
# --------------------------------------------------------- #
# 主页配置
index:
  # 首页标头文字
  title: 'hexo主题之delicate'
  # 首页按钮文字
  buttonText: 'go'
  # 阅读更多按钮
  excerpt:
    text: 'More'
