title: delicate

# Header
menu:
  Home: /
  Archives: /archives
  # 未实现
  # Categories: /categorie
  # 标签: /tags
  # 关于: /about

# Read More text
excerpt_link: 阅读更多


# --------------------------- #
##  siderbar infomation      ##
# --------------------------- #
## sidebar-about
siderbar:
  name: 陈科衡
  logo: Time wait for no one.
  tag: 
    - 学生
    - 前端开发者
    - hexo开发者
    - 上海海洋大学
    - delicate主题开发者
  social: 
    bilibili: https://space.bilibili.com/481922596
    github: https://github.com/can-dy-jack
    twitter: https://twitter.com/kartjim
    CSDN: https://blog.csdn.net/qq_46590483?spm=1000.2115.3001.5343
    codepen: https://codepen.io/Kartjim

# --------------------------- #
## 背景                      ##
# --------------------------- #
background: 
  # meditation | point | line | line2
  ## 如果不填或填其它值，就是默认的白色背景
  default: point

  # three.js
  # 如需要添加背景three.js，需要defaut: false
  ## 还没做好！
  threeJs: 
    enable: false
    ## 3D模型
    type: 





