# 站点配置中的 zh-cn 是中文

# --------------------------------------------------------- #
#
#                         router
#
# --------------------------------------------------------- #
router:
  tags: true
  categories: true
  page404: true
  # 可自定义页面: 在`source`文件夹下新建页面同名文件夹，文件夹下新建index.md文件
  custom_pages:
    about: 
      link: "about"
      text: "关于我"
    message:
      link: "message"
      text: "留言板"

# --------------------------------------------------------- #
#
#                      head and footer
#
# --------------------------------------------------------- #
## meta
# 当前文档的创建者
creator: ""
# 当前文档的发布者/出版者
publisher: ""

## link
# icon
icon: "/img/logo.ico"
# 导航栏上的图标
icon128: "/img/logo128.ico"

# nav友情链接
nav: 
  friends:
    github: "https://github.com/can-dy-jack/hexo-theme-delicate"
    dev.to: https://dev.to/kartjim
    LeetCode: "https://leetcode-cn.com/u/kartjim/"
    CSDN: "https://blog.csdn.net/qq_46590483"
    掘金: "https://juejin.cn/user/1389392813630526"


## footer - 建站起始时间
# 格式：- "2021-11-01T00:00:00"（默认本地时区）
# - "01 Nov 2021 00:00:00 +0800"（东八区，偏离格林威治8个小时）
startTime: "2021-11-01T00:00:00"

# --------------------------------------------------------- #
#
#                        styles
#
# --------------------------------------------------------- #
markdown_style:
  table_color: "#f6f6f6"
  table_tr_color: "rgb(246, 253, 253)"
  table_border_color: "#f6f6f6"
  blockquote:
    border_left_color: "#999"
    border_left_width: "5px"
    padding: "5px 12px"
    color: "gray"
  a:
    background: ''
    hoverBackground: ''

color:
  # a标签颜色
  a: "#34ae56"
  # 选中的文本颜色
  selection: "orange"
  selectionTextColor: "#fff"

# --------------------------------------------------------- #
#
#                   index and post
#
# --------------------------------------------------------- #
# 主页配置
index:
  # 首页标头文字
  title: "hexo主题之delicate"
  # 阅读更多按钮
  excerpt:
    text: "阅读更多"

# post页面
post:
  share:
    qq: true
    weibo: true

# --------------------------------------------------------- #
#
#       tags | tag | archive | category | categories
#
# --------------------------------------------------------- #
# 标签云 tagcloud 
## 前提：tags: true
tags: 
  # 标签云页面title
  title: ''
  # 最小字体尺寸
  min_font: 16
  # 最大字体尺寸
  max_font: 35
  # 字体尺寸的单位
  unit: 'px'
  # 标签总量
  amount: 900
  # 开始的颜色和结束的颜色
  ## 您可使用十六进位值（#b700ff），rgba（rgba(183, 0, 255, 1)），hsla（hsla(283, 100%, 50%, 1)）或 [颜色关键字]
  start_color: '#00eeee'
  end_color: '#004444'

# 单个标签页面
tag:
  aBackground: rgb(242, 248, 244)
  aHoverColor: rgb(54, 194, 200)
  aBorderRadius: 5px

# 归档页面
archive:
  aBackground: rgb(242, 248, 244)
  aHoverColor: rgb(54, 194, 100)
  aBorderRadius: 0
  boxShadow: 0 5px 20px rgba(0,0,0,.1)

categories:
  title: '分类'

  # 单个分类中折叠展示文章数的最大值，超过限制会显示 More，设为 0 则不限制
  post_limit: 5

  # 分类的排序字段，前面带减号是倒序
  # Options: length | name
  order_by: "name"

  # 层级的折叠深度，0 是全部折叠，大于 0 后如果存在子分类则默认展开
  collapse_depth: 0

  # 文章的排序字段，前面带减号是倒序，不带减号是正序
  # Options: date | title | or other field of front-matter
  post_order_by: "-date"

category: 
  aBackground: rgb(242, 248, 244)
  aHoverColor: rgb(54, 194, 200)
  aBorderRadius: 5px

# 分页
pagination:
  background: 'rgba(19, 198, 100, 0.1)'
  color: 'rgb(19, 198, 100)'

page404:
  title: ''
  subtitle: ''
  warning: ''
  # 几秒后跳转到主页
  startTime: 10

# --------------------------------------------------------- #
#
#          comments    评论功能
#
# --------------------------------------------------------- #
comments:
  # 参见：https://utteranc.es/
  utteranc: 
    # 打开评论  utteranc 不需要手动初始化
    enable: true
    # 设定仓库的地址，使用该仓库的issue作为评论的后台数据库
    repo: "can-dy-jack/delicate"
    # 可以指定主题
    theme: "github-light"
  # 畅言：http://changyan.kuaizhan.com/
  changyan:
    enable: false
    appid: 'cywauc17c'
    conf: 'prod_2a66ec8f42616f5d4232179c8ed63bc9'
  valine:
    enable: true
    app_id: "Wk9vQoRxLk28Q2uj976gWn1v-gzGzoHsz"
    app_key: "fgWmsNLv5wYNO8jdAXf5hvrG"
    avatar: wavatar # 头像样式(https://valine.js.org/avatar.html)
    visitor: true, # 阅读量统计
    placeholder: "参与评论"

