# header
title: delicate
menu:
  Home: /
  Archives: /archives

# footer - 建站起始时间
## 格式：
##- "2021-11-01T00:00:00"（默认本地时区）
##- "01 Nov 2021 00:00:00 +0800"（东八区，偏离格林威治8个小时）
startTime: "2021-11-01T00:00:00"

# --------------------------- #
##  siderbar infomation      ##
# --------------------------- #
## sidebar-about
siderbar:
  name: Kart · Jim
  logo: Time wait for no one.
  tag: 
    - student
    - front-end developer
    - hexo-theme-delicate
  social: 
    # social account link
    ## if the value is none or '',it does not apear.
    github: https://github.com/can-dy-jack
    twitter: 'http://localhost:4000'
    codepen: ''
    google: ''
    facebook: 'http://localhost:4000'
    stackoverflow: ''
    linkedin: ''
    slack: ''
    instagram: 'http://localhost:4000'
    gitlab: ''
    # for China
    bilibili: 
    CSDN: https://blog.csdn.net/qq_46590483?spm=1001.2100.3001.5343
    贴吧: ''
    知乎: ''
    微博: ''
    博客园: ''
    掘金: ''
    dingding: ''


# --------------------------- #
##       background          ##
# --------------------------- #
background: 
  # canvas制作的动态3D背景
  canvas: 
    enable: false
    # use rgb color,the value must be like "50,50,250"
    color: '128,64,224'
    # z-index
    zIndex: '-5'
    opacity: '0.7'
    # canvas line count
    count: '300'

  # three.js
  # 如需要添加背景three.js，需要关闭canvas背景
  ## 还没做好！
  threeJs: 
    enable: false
    ## 3D模型
    type: 

# available values: meditation | point | line | line2
backgroundStyle: ''



# --------------------------- #
##   style setting           ##
# --------------------------- #
# Read More text 
excerpt_link: 'Read More'
style: 
  # 置顶文章的样式
  ## 基于bootstrap，可选项即为bootstrap的alert样式;默认：'alert alert-light'
  ### more：https://v4.bootcss.com/docs/components/alerts/
  ## use,just like: 'alert alert-primary'
  top: 'alert alert-info'
  # '阅读更多' 的按钮样式
  ## 基于bootstrap，可选项即为bootstrap的按钮样式
  ## btn-primary | btn-secondary | btn-secondary | btn-outline-success  and so on.
  ## more: https://v4.bootcss.com/docs/components/buttons/
  ## just like: 'btn btn-outline-success';
  button: ''
  ## 各个组件的样式设置
  color:
    # body's background-color,default is #fafafa;
    body: '#fafafa'

    # menu's background-color,default is #fff;
    menu: ''
    # menu's box-shadow,default is none;
    menuBoxShadow: '0 -2px 12px 2px rgba(0,0,0,.1)'

    # post's background-color,default is #fff;
    post: ''
    ## post's box-shadow
    postBoxShadow: '2px 4px 18px rgba(30,30,30,.05)'

    # header's background-color,default is #fff;
    header: ''
    # header's border-radius,default is 0px;
    headerBorderRadius: ''
    # header's box-shadow,default is none;
    headerBoxShadow: ''
  siderbar: 
    # sidebar social-icon color and hover-color
    color: '#999'
    hoverColor: '#008080'

# 鼠标点击效果；
## showText / showHeart / firework 只能打开一个！否则 鼠标点击效果为最靠上的那一个。
mouseClick: 
  # 点击出现文字效果
  showText:
    enable: false
    text: ['css','HTMl','JavaScript','Hexo','ejs']
    color: 'red'
  # 鼠标点击 - 心形
  ## 心是随机颜色。
  showHeart: false
  # 鼠标点击 - 烟花爆炸效果
  firework: true


# --------------------------- #
##   widget                 ##
# --------------------------- #
widget:
  # 诗句 - 颜色和诗句随机生成
  poem: false
  # 显示实时天气
  ## 仅限于 中国地区城市
  weather: 
    enable: false
    # 直接打城市名字即可
    city: '上海'
    openBroadcast: false
  music: 
    enable: true



# --------------------------- #
##   plugins                 ##
# --------------------------- #
# 图片查看插件
fancybox:
  enable: true


# --------------------------- #
##   评论系统                 ##
# --------------------------- #
utterance: 
## 仓库需要安装utterances https://github.com/apps/utterances
  enable: false
  repo: 
  issue_term: delicate-utterance
  # github-light | github-dark | preferred-color-scheme | github-dark-orange | icy-dark | dark-blue | photon-dark | boxy-light | gruvbox-dark
  ## 在线观看每个主题效果：https://utteranc.es/
  theme: 'github-light'

gittalk: 
  ## Firstly, you need choose a public github repository for store comment.
  ## A GitHub Application : https://github.com/settings/applications/new
  ### more: https://github.com/gitalk/gitalk
  enable: false
  # 您的评论存放的仓库名字
  repo: ''
  owner: ''
  admin: ['',]
  # GitHub Application Client ID and Client Secret
  clientID: ''
  clientSecret: ''
