# 站点配置中的 zh-cn 是中文

# --------------------------------------------------------- #
#
#                         router
#
# --------------------------------------------------------- #
router:
  tags: true
  categories: true
  page404: true
  # 可自定义页面: 在`source`文件夹下新建页面同名文件夹，文件夹下新建index.md文件
  custom_pages:
    # new file "index.md" in new folder "about"
    about: 
      link: "about"
      text: "关于我"
    # also, you can create a new file "other.md" in folder "about" and configure it
    # other: 
      # link: "about/other"
      # text: "other"
    message:
      link: "message"
      text: "留言板"

# --------------------------------------------------------- #
#
#                      head and footer
#
# --------------------------------------------------------- #
## meta
# 当前文档的创建者
creator: ""
# 当前文档的发布者/出版者
publisher: ""

## link
# icon
icon: "/img/logo.ico"
# 导航栏上的图标
icon128: "/img/logo128.ico"

# nav友情链接
nav: 
  friends:
    github: "https://github.com/can-dy-jack/hexo-theme-delicate"
    dev.to: https://dev.to/kartjim
    LeetCode: "https://leetcode-cn.com/u/kartjim/"
    CSDN: "https://blog.csdn.net/qq_46590483"
    掘金: "https://juejin.cn/user/1389392813630526"


## footer - 建站起始时间
# 格式：- "2021-11-01T00:00:00"（默认本地时区）
# - "01 Nov 2021 00:00:00 +0800"（东八区，偏离格林威治8个小时）
startTime: "2021-11-01T00:00:00"

# --------------------------------------------------------- #
#
#                        styles
#
# --------------------------------------------------------- #
markdown_style:
  # 代码块样式 
  ## 可选：one light | one dark | github | github dark | monokai | solarized light | solarized dark
  ## 想要更多样式？提交issue：https://github.com/can-dy-jack/hexo-theme-delicate
  code_styles: "solarized light"
  blockquote:
    border_left_color: "#999"
    border_left_width: "5px"
    padding: "5px 12px"
    color: "gray"
  a:
    background: 'rgba(217, 249, 253)'
    hoverBackground: 'rgb(187, 239, 253)'
  inline_code:
    bgcolor: 'rgba(0, 0, 0, .1)'
    color: '#27c93f'
  toc:
    color: rgb(208, 0, 88)
    list_bg: rgba(255, 213, 228, .5)
    item_bg: rgba(255, 213, 228, .3)

color:
  # a标签颜色, 基本色
  a: "#34ae56"
  # 选中的文本颜色
  selection: "rgba(255, 165, 0, .2)"
  selectionTextColor: "inherit"

mermaid: 
  theme: forest
  # true or false
  startOnLoad: true
  arrowMarkerAbsolute: false

# --------------------------------------------------------- #
#
#                   index and post
#
# --------------------------------------------------------- #
# 主页配置
index:
  # 首页标头文字
  title: "hexo主题之delicate"
  # 阅读更多按钮
  excerpt:
    text: "阅读更多"

# post页面
post:
  share:
    qq: true
    weibo: true

# --------------------------------------------------------- #
#
#       tags | tag | archive | category | categories
#
# --------------------------------------------------------- #
# 标签云 tagcloud 
## 前提：tags: true
tags: 
  # 标签云页面title
  title: ''
  # 最小字体尺寸
  min_font: 16
  # 最大字体尺寸
  max_font: 35
  # 字体尺寸的单位
  unit: 'px'
  # 标签总量
  amount: 900
  # 开始的颜色和结束的颜色
  ## 您可使用十六进位值（#b700ff），rgba（rgba(183, 0, 255, 1)），hsla（hsla(283, 100%, 50%, 1)）或 [颜色关键字]
  start_color: '#00ff00'
  end_color: '#004444'

# 单个标签页面
tag:
  aBackground: rgba(54, 194, 200, .1)
  aHoverColor: rgb(54, 194, 200)
  aBorderRadius: 5px

# 归档页面
archive:
  aBackground: rgba(250, 12, 12, .1)
  aHoverColor: red
  aBorderRadius: 0
  boxShadow: 0 5px 20px rgba(0,0,0,.1)

categories:
  title: '分类'

  # 单个分类中折叠展示文章数的最大值，超过限制会显示 More，设为 0 则不限制
  post_limit: 5

  # 分类的排序字段，前面带减号是倒序
  # Options: length | name
  order_by: "name"

  # 层级的折叠深度，0 是全部折叠，大于 0 后如果存在子分类则默认展开
  collapse_depth: 0

  # 文章的排序字段，前面带减号是倒序，不带减号是正序
  # Options: date | title | or other field of front-matter
  post_order_by: "-date"

category: 
  aBackground: rgba(242, 248, 0, .1)
  aHoverColor: rgb(242, 248, 0)
  aBorderRadius: 5px

# 分页
pagination:
  background: 'rgba(19, 198, 100, 0.1)'
  color: 'rgb(19, 198, 100)'

page404:
  title: ''
  subtitle: ''
  warning: ''
  # 几秒后跳转到主页
  startTime: 10

# --------------------------------------------------------- #
#
#          comments    评论功能
#
# --------------------------------------------------------- #
comments:
  # 参见：https://utteranc.es/
  utteranc: 
    # 打开评论  utteranc 不需要手动初始化
    enable: false
    # 设定仓库的地址，使用该仓库的issue作为评论的后台数据库
    repo: "can-dy-jack/delicate"
    # 可以指定主题
    theme: "github-light"
  # 畅言：http://changyan.kuaizhan.com/
  changyan:
    enable: false
    appid: ''
    conf: ''
  # https://valine.js.org
  valine:
    enable: false
    app_id: ""
    app_key: ""
    avatar: wavatar # 头像样式(https://valine.js.org/avatar.html)
    visitor: true, # 阅读量统计
    placeholder: "参与评论"
  # https://disqus.com/profile/signup/
  disqus:
    enable: false
    mainJs: "//hexozhu-ti-zhi-delicate.disqus.com/embed.js"
    countJs: "//hexozhu-ti-zhi-delicate.disqus.com/count.js"
  gitalk:
    # 首先，您需要选择一个公共github存储库（已存在或创建一个新的github存储库）用于存储评论
    # 然后需要创建 GitHub Application，如果没有 点击 https://github.com/settings/applications/new 申请
    # Authorization callback URL 填写当前使用插件页面的域名。
    # 获取生成的 clientID 、clientSecret
    enable: false
    clientID: 
    clientSecret: 
    repo: delicate
    owner: can-dy-jack
    # 支持 [en, zh-CN, zh-TW, es-ES, fr, ru, de, pl, ko, fa, ja]
    language: zh-CN
  gitment:
    enable: false
    clientID: 
    clientSecret: 
    repo: delicate
    owner: can-dy-jack
  vssue:
    # 依赖 vue，需要加载vue，可能会使页面加载变慢
    enable: false
    # github https://vssue.js.org/zh/guide/github.html 
    # | gitlab https://vssue.js.org/zh/guide/gitlab.html
    # | bitbucket https://vssue.js.org/zh/guide/bitbucket.html
    # | gitee https://vssue.js.org/zh/guide/gitee.html
    # | gitea https://vssue.js.org/zh/guide/gitea.html
    platform: "github"
    clientID: 
    clientSecret: 
    repo: delicate
    owner: can-dy-jack
  livere:
    # https://livere.com/ 来必力City版
    enable: false
    dataUid:
  giscus: 
    # A comment system powered by GitHub Discussions. 
    # https://giscus.app/
    # 确保： 
    ## 此仓库是公开的
    ## 此仓库 giscus app 已安装
    ## Discussions功能已在你的仓库中启用。 
    enable: true
    # 注意：JSON Viewer相关浏览器插件会影响该评论系统的显示
    repo: can-dy-jack/delicate
    repoId: R_kgDOGVfGBw
    category: Q&A
    categoryId: DIC_kwDOGVfGB84CQqqh
    mapping: title
    inputPosition: top # top | bottom
    theme: light
    lang: zh-CN


# --------------------------------------------------------- #
#
#                         CDN
#
# --------------------------------------------------------- #
CDN:
  mathjax: https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML
  mermaid: https://unpkg.com/mermaid@7.1.2/dist/mermaid.min.js
  gitalkStyle: https://unpkg.com/gitalk/dist/gitalk.css
  gitmentStyle: https://imsun.github.io/gitment/style/default.css
  vssueStyle: https://unpkg.com/vssue/dist/vssue.min.css
